from pathlib import Path
from typing import Tuple, Union

import numpy as np
import pandas as pd

from src.dq_layer.dq import find_bad_data, write_bad_data
from src.logger.log import get_logger
from src.utils.file_reader import FileReader

logger = get_logger(__name__)


def load_bronze_parquet_data(
    transactions_path: Union[str, Path] = "src/bronze/transactions.parquet",
    settlements_path: Union[str, Path] = "src/bronze/settlements.parquet",
    upi_path: Union[str, Path] = "src/bronze/upi_responses.parquet",
    dq_target_dir: Union[str, Path] = "src/bad_data",
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Read Parquet bronze files generated by the ingestion layer and persist bad records."""
    transactions = FileReader(transactions_path, file_type="parquet").data
    settlements = FileReader(settlements_path, file_type="parquet").data
    upi = FileReader(upi_path, file_type="parquet").data

    bad_data = find_bad_data(transactions, settlements, upi)
    if bad_data:
        write_bad_data(bad_data, dq_target_dir)

    return transactions, settlements, upi


def process_reconciliation(
    transactions: pd.DataFrame,
    settlements: pd.DataFrame,
    upi: pd.DataFrame,
    target_dir: Path | str = "src/silver",
) -> Path:
    """Apply reconciliation transformations and write the result to Parquet.

    Args:
        transactions: Transaction dataframe.
        settlements: Settlement dataframe.
        upi: UPI response dataframe.
        target_dir: Directory where the reconciled parquet file will be written.

    Returns:
        Path to the written Parquet file.
    """
    target_dir = Path(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / "reconciled.parquet"

    logger.info("Starting reconciliation and writing output to %s", target_path)

    settlements = settlements.copy()
    transactions = transactions.copy()
    upi = upi.copy()

    settlements["settlement_date"] = pd.to_datetime(
        settlements["settlement_date"], format="%d-%m-%Y", errors="coerce"
    )
    settlements.rename(columns={"txn_id": "settlement_txn_id"}, inplace=True)

    transactions["timestamp"] = pd.to_datetime(transactions["timestamp"], errors="coerce")
    transactions["expected_settlement_date"] = (
        transactions["timestamp"].dt.date + pd.Timedelta(days=1)
    )
    transactions["expected_settlement_date"] = pd.to_datetime(
        transactions["expected_settlement_date"], errors="coerce"
    )

    upi.rename(
        columns={
            "txn_id": "upi_txn_id",
            "timestamp": "upi_timestamp",
            "response_code": "upi_response_code",
        },
        inplace=True,
    )

    reconciled = transactions.merge(
        upi,
        left_on="txn_id",
        right_on="upi_txn_id",
        how="left",
    )

    reconciled = reconciled.merge(
        settlements,
        left_on="txn_id",
        right_on="settlement_txn_id",
        how="left",
    )

    reconciled["internal_amount"] = reconciled["amount"]
    reconciled["settled_amount"] = reconciled["settled_amount"].astype("float64")
    reconciled["difference"] = reconciled["internal_amount"] - reconciled["settled_amount"]

    reconciled["status"] = np.select(
        [
            reconciled["settled_amount"].isna(),
            reconciled["difference"].abs() <= 1,
            reconciled["difference"].abs() > 1,
        ],
        ["missing_in_settlement", "matched", "mismatch"],
        default="missing_in_settlement",
    )

    if "upi_response_code" not in reconciled.columns:
        if "response_code" in reconciled.columns:
            reconciled["upi_response_code"] = reconciled["response_code"]
        elif "code" in reconciled.columns:
            reconciled["upi_response_code"] = reconciled["code"]
        else:
            reconciled["upi_response_code"] = pd.NA

    reconciled["ingestion_timestamp"] = pd.Timestamp.now(tz="UTC")

    result_columns = [
        "txn_id",
        "internal_amount",
        "settled_amount",
        "difference",
        "status",
        "upi_response_code",
        "ingestion_timestamp",
    ]

    reconciled_result = reconciled.loc[:, result_columns]
    reconciled_result.to_parquet(target_path, index=False)
    logger.info("Reconciliation complete and written to %s", target_path)
    return target_path
